services:
  frontend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"